[package]
name = "rune_etcher_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.4.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "scarb test"
build = "scarb build"
